export default [
{
    "docker-preprod.intuit.com/personal/spr01/alpine": {
      "latest": {
        "Name": "docker-preprod.intuit.com/personal/spr01/alpine",
        "Tag": "latest",
        "Created": "2022-11-10T11:05:41.393518Z",
        "Labels": null,
        "Architecture": "amd64",
        "Variant": "",
        "Os": "linux",
        "Env": [
          "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Author": "",
        "History": [
          "ADD file:2a949686d9886ac7c10582a6c29116fd29d3077d02755e87e111870d63607725 in /",
          "CMD [\"/bin/sh\"]"
        ]
      }
    },
    "docker-preprod.intuit.com/personal/spr01/oicp/standard/java/amzn-corretto-jdk17": {
      "latest": {
        "Name": "docker-preprod.intuit.com/personal/spr01/oicp/standard/java/amzn-corretto-jdk17",
        "Tag": "latest",
        "Created": "2022-11-10T11:05:41.393518Z",
        "Labels": {
          "HOME_URL": "https://amazonlinux.com/",
          "PRETTY_NAME": "Amazon Linux 2",
          "base.build_date": "2022-11-14T11:15:11Z",
          "base.description": "Intuit Amazon Linux 2 Base Image",
          "base.maintainer": "TechArtifactSupport@intuit.com",
          "com.intuit.amzn-corretto-jdk17_semantic_version": "2.2.2",
          "com.intuit.amzn_baseline_image_semantic_version": "1.1.39",
          "com.intuit.appd_java_agent_version": "22.10.0.34344",
          "com.intuit.base.amzn_version": "2",
          "com.intuit.base.intuit_version": "1.1.39",
          "com.intuit.contrast_java_agent_version": "4.0.0",
          "com.intuit.corretto_version": "17.0.5.8",
          "com.intuit.demo_version": "1.7.2",
          "com.intuit.jacoco_java_agent_version": "0.8.8",
          "com.intuit.stash_version": "3.96.0",
          "description": "This image can be used as a base image for other applications based on Java. The Corretto image can be extended using the CPD utility.",
          "image_file": "amzn2-container-raw-2.0.20221004.0-x86_64",
          "intuit_ap_sw": "corretto",
          "intuit_ap_sw_version": "17.0.5.8",
          "io.buildah.version": "1.28.0",
          "lineage": "[\n   {\n      \"ASSET_URL\": \"N/A\",\n      \"CHECKMARX_SCAN_RISK_SEVERITY\": \"\",\n      \"CHECKMARX_SCAN_LINK\": \"\",\n      \"CPD_GIT_HASH\": \"6dfed1a650be78f4dbb3c7746da607d5fa5c7f27\",\n      \"CPD_MAJOR_VERSION\": \"N/A\",\n      \"CPD_VERSION\": \"2.0.1\",\n      \"DOCKERFILE_LINK\": \"https://ffd7ce72995ed3b0070b76f2c72ecd173005300a%40github.intuit.com/dev-patterns/ap_corretto_container/blob/master/Dockerfile\",\n      \"EXCEPTION_CVE_LIST\": \"N/A\",\n      \"FROM\": \"docker.intuit.com/oicp/standard/base/amzn:1.1.39\",\n      \"FROM_IMAGE_DIGEST\": [\n         \"docker.intuit.com/oicp/standard/base/amzn@sha256:4e096f4d10529bea1d70ea8c678927363932cdd07a2d883c05b931727ac22df3\"\n      ],\n      \"GIT_COMMIT_HASH\": \"ce6b1ccdf1b08a0c36f6cd5b2461c101dc6f5413\",\n      \"GITHUB_BRANCH\": \"master\",\n      \"GITHUB_COMMIT_AUTHOR\": \"aramsamy arasu_ramasamy@intuit.com\",\n      \"GITHUB_COMMIT_TIME\": \"2022-11-14T13:40:02Z\",\n      \"GITHUB_LINK\": \"https://ffd7ce72995ed3b0070b76f2c72ecd173005300a%40github.intuit.com/dev-patterns/ap_corretto_container\",\n      \"IQSERVER_HIGHEST_THREAT_LEVEL\": \"\",\n      \"IQSERVER_POLICY_VIOLATIONS\": null,\n      \"IQSERVER_SCAN_LINK\": \"\",\n      \"JIRA_ISSUE\": \"N/A\",\n      \"JIRA_PROJECT\": \"Unknown\",\n      \"MAINTAINER\": \"idevp-patterns-team@intuit.com\",\n      \"UNAUTHORIZED_SOURCE_IMAGES\": [\n         \"N/A\"\n      ]\n   }\n]",
          "maintainer": "idevp-patterns-team@intuit.com",
          "recipe_id": "a0f48d18-a028-7835-5f63-be90-6cae-a6a7-d1bef075",
          "summary": "Build a Docker image containing Corretto, which is Amazon's implementation of OpenJDK.",
          "vcs_url": "https://github.intuit.com/dev-patterns/ap_corretto.git"
        },
        "Architecture": "amd64",
        "Variant": "",
        "Os": "linux",
        "Env": [
          "USER_HOME=/home/appuser",
          "COMMENTS=Intuit Application User",
          "USERNAME=appuser",
          "USER_UID=1000",
          "PACKAGES=        sudo         tar         openssl         shadow-utils         ",
          "JAVA_HOME=/usr/lib/jvm/amazon-corretto-17.0.5.8.1-linux-x64",
          "PATH=/usr/lib/jvm/amazon-corretto-17.0.5.8.1-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Author": "",
        "History": [
          "ADD file:33ce740675602f8911c110c617b08d74ebe9c26c82226b4815019d8c2d0a2263 in /",
          "CMD [\"/bin/bash\"]",
          "FROM docker.intuit.com/docker-rmt/amazonlinux:latest",
          "# /bin/sh -c yum update --security -y     && yum clean all     && rm -rf /var/cache/yum",
          "LABEL \"PRETTY_NAME\"=\"Amazon Linux 2\"",
          "LABEL \"image_file\"=\"amzn2-container-raw-2.0.20221004.0-x86_64\"",
          "LABEL \"recipe_id\"=\"a0f48d18-a028-7835-5f63-be90-6cae-a6a7-d1bef075\"",
          "LABEL \"HOME_URL\"=\"https://amazonlinux.com/\"",
          "FROM docker.intuit.com/oicp/base/amazonlinux:2",
          "# ARG INTUIT_VERSION",
          "ARG AMAZONLINUX_VERSION INTUIT_VERSION",
          "ARG AMAZONLINUX_VERSION BUILD_DATE INTUIT_VERSION",
          "ARG AMAZONLINUX_VERSION BUILD_DATE DOCKER_IMAGE_NAME INTUIT_VERSION",
          "LABEL base.description=\"Intuit Amazon Linux 2 Base Image\"     base.maintainer=\"TechArtifactSupport@intuit.com\"     base.build_date=${BUILD_DATE}     vcs_url=\"https://github.intuit.com/dev-patterns/docker-oicp-amazonlinux.git\"     com.intuit.base.intuit_version=${INTUIT_VERSION}     com.intuit.base.amzn_version=${AMAZONLINUX_VERSION}",
          "ENV USER_HOME=/home/appuser     COMMENTS=\"Intuit Application User\"     USERNAME=appuser     USER_UID=1000",
          "ENV PACKAGES=\"        sudo         tar         openssl         shadow-utils         \"",
          "ONBUILD RUN [\"/bin/cat\", \"/etc/future\"]",
          "|4 AMAZONLINUX_VERSION=2 BUILD_DATE=2022-11-14T11:15:11Z DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/base/amzn:1.1.39 INTUIT_VERSION=1.1.39 /bin/sh -c     sed -i '1i\\[amzn2-intuit]\\nname=Intuit Amazon Linux 2 Repository\\nbaseurl=https://artifact.intuit.com/artifactory/amzn2-intuit/     \\npriority=10\\nenabled=1\\ngpgcheck=0\\n ' /etc/yum.repos.d/amzn2-core.repo     && yum update -y --security     && yum install -y ${PACKAGES}     && mkdir -p ${USER_HOME}     && groupadd ${USERNAME}     && useradd -l -u ${USER_UID} -r -g ${USER_UID} -d ${USER_HOME} -s /sbin/nologin -c \"${COMMENTS}\" ${USERNAME}     && groupmod -g 1000 ${USERNAME}     && echo \"${USERNAME} ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers     && chown -R ${USERNAME}:0 ${USER_HOME}     && chmod -R g+rw ${USER_HOME}     && yum remove -y shadow-utils     && yum clean all     && rm -rf /var/cache/yum/*",
          "COPY multi:ff4d7e28a976715d9de601ebd5c44c3270a4b1c188c8c676e765ae0a57d4dea3 in ${USER_HOME}/",
          "COPY file:88137df33081a381d7cf6c0d07480be8864f1a9bc87df999507e9e8e31ca9dbc in /root",
          "|4 AMAZONLINUX_VERSION=2 BUILD_DATE=2022-11-14T11:15:11Z DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/base/amzn:1.1.39 INTUIT_VERSION=1.1.39 /bin/sh -c chmod +x ${USER_HOME}/harden.sh     && chmod +x ${USER_HOME}/post_harden.sh     && ${USER_HOME}/harden.sh",
          "WORKDIR ${USER_HOME}",
          "USER ${USERNAME}",
          "CMD [ \"bash\" ]",
          "ARG BUILD_DATE=22.11.14",
          "ARG BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8",
          "ARG BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable",
          "ARG BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable JIRA_PROJECT=https://jira.intuit.com/projects/AMI",
          "ARG BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable JAVA_VER=java-17 JIRA_PROJECT=https://jira.intuit.com/projects/AMI",
          "ENV JAVA_HOME=/usr/lib/jvm/amazon-corretto-17.0.5.8.1-linux-x64",
          "ENV PATH=\"${JAVA_HOME}/bin:${PATH}\"",
          "LABEL summary=\"Build a Docker image containing Corretto, which is Amazon's implementation of OpenJDK.\"   description=\"This image can be used as a base image for other applications based on Java. The Corretto image can be extended using the CPD utility.\"   maintainer=\"idevp-patterns-team@intuit.com\"   vcs_url=\"https://github.intuit.com/dev-patterns/ap_corretto.git\"   intuit_ap_sw=\"corretto\"   intuit_ap_sw_version=\"17.0.5.8\"   com.intuit.amzn_baseline_image_semantic_version=\"1.1.39\"   com.intuit.corretto_version=\"17.0.5.8\"   com.intuit.appd_java_agent_version=\"22.10.0.34344\"   com.intuit.jacoco_java_agent_version=\"0.8.8\"   com.intuit.contrast_java_agent_version=\"4.0.0\"   com.intuit.demo_version=\"1.7.2\"   com.intuit.stash_version=\"3.96.0\"",
          "COPY file:b7f941c43852c40790d32f35019343b1c99f3cfa7ddd546df4f4968b49457792 in /goss/goss.yaml",
          "USER root",
          "|5 BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable JAVA_VER=java-17 JIRA_PROJECT=https://jira.intuit.com/projects/AMI /bin/sh -c yum -y install curl unzip   && curl -sLo /tmp/corretto_install.tar.gz https://artifact.intuit.com/artifactory/generic-local/dev/patterns/ap/team/corretto/amazon-corretto-17.0.5.8.1-linux-x64.tar.gz   && (md5sum /tmp/corretto_install.tar.gz | grep -c \"332e554fd50993b836b0f8fc1674b0dc\" || (echo \"Bad md5 sum, expecting '332e554fd50993b836b0f8fc1674b0dc' for https://artifact.intuit.com/artifactory/generic-local/dev/patterns/ap/team/corretto/amazon-corretto-17.0.5.8.1-linux-x64.tar.gz\"; exit 1))   && umask 022   && mkdir -p /usr/lib/jvm   && tar -zxvf /tmp/corretto_install.tar.gz -C /usr/lib/jvm   && rm -f /tmp/corretto_install.tar.gz   && ln -s /usr/lib/jvm/amazon-corretto-17.0.5.8.1-linux-x64 /usr/lib/jvm/java-17-amazon-corretto   && mkdir -p /usr/java   && ln -s /usr/lib/jvm/amazon-corretto-17.0.5.8.1-linux-x64 /usr/java/java-17-amazon-corretto   && ln -s /usr/java/java-17-amazon-corretto /usr/java/default  && ln -s /usr/java/default /usr/java/latest   && ln -s /usr/java/default/bin/java /usr/bin/java   && chown -R 0:0 /usr/lib/jvm/amazon-corretto-17.0.5.8.1-linux-x64",
          "|5 BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable JAVA_VER=java-17 JIRA_PROJECT=https://jira.intuit.com/projects/AMI /bin/sh -c curl --create-dirs -sLo /app/contrast/javaagent/contrast.jar https://artifact.intuit.com/artifactory/generic-local/dev/security/ssdlc/contrast/java/4.0.0/contrast.jar",
          "|5 BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable JAVA_VER=java-17 JIRA_PROJECT=https://jira.intuit.com/projects/AMI /bin/sh -c curl --create-dirs -sLo /app/jacoco/jacoco-agent-runtime.jar https://artifact.intuit.com/artifactory/generic-local/dev/patterns/ap/team/jacoco-agent-runtime-0.8.8.jar",
          "|5 BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable JAVA_VER=java-17 JIRA_PROJECT=https://jira.intuit.com/projects/AMI /bin/sh -c curl --create-dirs -sLo /app/AppServerAgent-1.8-22.10.0.34344.zip https://artifact.intuit.com/artifactory/generic-intuit/dev/patterns/ap/team/appagent/AppServerAgent-1.8-22.10.0.34344.zip   && unzip -oq /app/AppServerAgent-1.8-22.10.0.34344.zip -d /app/appdynamics/   && rm -f /app/AppServerAgent-1.8-22.10.0.34344.zip",
          "|5 BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable JAVA_VER=java-17 JIRA_PROJECT=https://jira.intuit.com/projects/AMI /bin/sh -c curl --create-dirs -sLo /tmp/stash-3.96.0-linux-glibc.tgz https://artifact.intuit.com/artifactory/generic-local/dev/patterns/ap/team/stash/stash-3.96.0-linux-glibc.tgz   && tar xzf /tmp/stash-3.96.0-linux-glibc.tgz -C /usr/bin/   && chown 0:0 /usr/bin/stash   && chmod 755 /usr/bin/stash   && rm -f /tmp/stash-3.96.0-linux-glibc.tgz",
          "|5 BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable JAVA_VER=java-17 JIRA_PROJECT=https://jira.intuit.com/projects/AMI /bin/sh -c chown -R appuser:appuser /app   && yum -y remove unzip   && yum clean all   && rm -rf /var/cache/yum/*",
          "|5 BUILD_DATE=22.11.14 DOCKER_IMAGE_NAME=docker.intuit.com/dev/patterns/ap/team/corretto-17.x/amzn2-corretto:17.0.5.8 DOCKER_TAGS=17:17.0:17.0.5:17.0.5.8:17.0.5.8-22.11.14:latest:stable JAVA_VER=java-17 JIRA_PROJECT=https://jira.intuit.com/projects/AMI /bin/sh -c sed -i -e 's/EC keySize < 224, 3DES_EDE_CBC, anon, NULL/EC keySize < 224, 3DES_EDE_CBC, anon, NULL, TLSv1, TLSv1.1/g' /usr/lib/jvm/java-17-amazon-corretto/conf/security/java.security",
          "USER appuser",
          "CMD [\"java\", \"--version\"]",
          "java --version"
        ]
      }
    },
    "docker-preprod.intuit.com/personal/spr01/oicp/standard/lambda/debian11-lambda-python": {
      "latest": {
        "Name": "docker-preprod.intuit.com/personal/spr01/oicp/standard/lambda/debian11-lambda-python",
        "Tag": "latest",
        "Created": "2022-11-10T11:05:41.393518Z",
        "Labels": {
          "BUILD_DATE": "2022-11-04T10:47:52Z",
          "INTUIT_VERSION": "1.0.22",
          "base.build_date": "2022-11-04T10:47:52Z",
          "base.description": "Lambda Runtime Interface Client for Python",
          "base.maintainer": "TechArtifactSupport@intuit.com",
          "com.intuit.base.debian_version": "11.5",
          "com.intuit.base.intuit_version": "1.0.22",
          "docker.label.com.intuit.debian11-lambda-python3.9_semantic_version": "1.0.2",
          "docker.label.com.intuit.python_pip_version": "22.0.4",
          "docker.label.com.intuit.python_version": "3.9.15",
          "io.buildah.version": "1.27.0",
          "lineage": "[\n   {\n      \"ASSET_URL\": \"N/A\",\n      \"CHECKMARX_SCAN_RISK_SEVERITY\": \"\",\n      \"CHECKMARX_SCAN_LINK\": \"\",\n      \"CPD_GIT_HASH\": \"6dfed1a650be78f4dbb3c7746da607d5fa5c7f27\",\n      \"CPD_MAJOR_VERSION\": \"N/A\",\n      \"CPD_VERSION\": \"2.0.1\",\n      \"DOCKERFILE_LINK\": \"https://github.intuit.com/dev-patterns/docker-oicp-debian-lambda-python/blob/HEAD/Dockerfile\",\n      \"EXCEPTION_CVE_LIST\": \"N/A\",\n      \"FROM\": \"\",\n      \"FROM_IMAGE_DIGEST\": null,\n      \"GIT_COMMIT_HASH\": \"59df21b4e7cf3cce4fa5b064dcce3c544fa3ed98\",\n      \"GITHUB_BRANCH\": \"HEAD\",\n      \"GITHUB_COMMIT_AUTHOR\": \"aramsamy Arasu_Ramasamy@intuit.com\",\n      \"GITHUB_COMMIT_TIME\": \"2022-11-10T10:51:10Z\",\n      \"GITHUB_LINK\": \"https://github.intuit.com/dev-patterns/docker-oicp-debian-lambda-python\",\n      \"IQSERVER_HIGHEST_THREAT_LEVEL\": \"\",\n      \"IQSERVER_POLICY_VIOLATIONS\": null,\n      \"IQSERVER_SCAN_LINK\": \"\",\n      \"JIRA_ISSUE\": \"N/A\",\n      \"JIRA_PROJECT\": \"Unknown\",\n      \"MAINTAINER\": \"\",\n      \"UNAUTHORIZED_SOURCE_IMAGES\": [\n         \"N/A\"\n      ]\n   }\n]",
          "vcs_url": "https://github.intuit.com/dev-patterns/docker-oicp-debian-lambda-python.git"
        },
        "Architecture": "amd64",
        "Variant": "",
        "Os": "linux",
        "Env": [
          "USERNAME=appuser",
          "USER_HOME=/home/appuser",
          "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
          "LANG=C.UTF-8",
          "PYTHON_VERSION=3.9.15",
          "PYTHON_PIP_VERSION=22.0.4",
          "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/b60e2320d9e8d02348525bd74e871e466afdf77c/get-pip.py",
          "PYTHON_GET_PIP_SHA256=c3b81e5d06371e135fb3156dc7d8fd6270735088428c4a9a5ec1f342e2024565"
        ],
        "Author": "",
        "History": [
          "ADD file:8644a8156a07a656a35c41e2b2a458befb660309f8592e3efd5b43d46156cec2 in /",
          "CMD [\"bash\"]",
          "FROM docker.intuit.com/docker-rmt/debian:11-slim",
          "# /bin/sh -c apt-get update     && apt-get install -y apt-transport-https curl gnupg apt-utils     && curl -X GET https://artifact.intuit.com/artifactory/api/gpg/key/public > artifactory-public.key.asc     && apt-key add artifactory-public.key.asc     && apt update -y     && apt upgrade -y     && rm -f artifactory-public.key.asc     && apt-get autoremove -y gnupg curl     && rm -rf /var/lib/apt/lists/*     && apt-get clean",
          "FROM docker.intuit.com/oicp/base/debian11:11.5",
          "# ARG BASE_TAG",
          "ARG BASE_TAG INTUIT_VERSION",
          "ARG BASE_TAG BUILD_DATE INTUIT_VERSION",
          "ARG BASE_TAG BUILD_DATE DOCKER_IMAGE_NAME INTUIT_VERSION",
          "LABEL base.description=\"Intuit Debian11 (Bullseye) Base Image\"     base.maintainer=\"TechArtifactSupport@intuit.com\"     base.build_date=${BUILD_DATE}     vcs_url=\"https://github.intuit.com/dev-patterns/docker-oicp-debian11.git\"     com.intuit.base.intuit_version=${INTUIT_VERSION}     com.intuit.base.debian_version=${BASE_TAG}     INTUIT_VERSION=${INTUIT_VERSION}     BUILD_DATE=${BUILD_DATE}",
          "ENV USERNAME ${USERNAME:-appuser}",
          "ENV USER_HOME ${USER_HOME:-/home/${USERNAME}}",
          "ONBUILD RUN [\"/bin/cat\", \"/etc/future\"]",
          "|4 BASE_TAG=11.5 BUILD_DATE=2022-11-04T10:47:52Z DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/base/debian11:1.0.22 INTUIT_VERSION=1.0.22 /bin/sh -c     useradd -ms /bin/bash ${USERNAME} -u 1000 -G sudo     && chown -R ${USERNAME}:${USERNAME} ${USER_HOME}",
          "WORKDIR ${USER_HOME}",
          "COPY multi:4b6fff73f93b29d437edb81cfb8ebc2f0b8657fd35a753ca1a74952a7af4a98a in ${USER_HOME}/",
          "COPY file:338c7a73ad1a2a921a67763b45c7a298a215e8f293a8c29989048506881d19d5 in /etc/apt/",
          "|4 BASE_TAG=11.5 BUILD_DATE=2022-11-04T10:47:52Z DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/base/debian11:1.0.22 INTUIT_VERSION=1.0.22 /bin/sh -c   echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections   && apt-get update   && apt-get install -y --no-install-recommends libncurses5-dev libncursesw5-dev apt-utils sudo vim-tiny   && apt update -y   && apt upgrade -y   && echo \"${USERNAME} ALL=(ALL:ALL) NOPASSWD:ALL\" >> /etc/sudoers   && chmod +x ${USER_HOME}/harden.sh   && chmod +x ${USER_HOME}/post_harden.sh   && cp .bashrc /root   && rm -f /bin/sh && ln -s /bin/bash /bin/sh   && rm -rf /var/lib/apt/lists/*   && apt-get clean   && ${USER_HOME}/harden.sh",
          "USER ${USERNAME}",
          "CMD [ \"bash\" ]",
          "FROM docker.intuit.com/oicp/standard/base/debian11:latest",
          "# ARG LAMBDA_APP_VERSION",
          "ARG DOCKER_TAGS LAMBDA_APP_VERSION",
          "ARG DOCKER_TAGS LAMBDA_APP_VERSION",
          "ARG DOCKER_TAGS LAMBDA_APP_VERSION PYTHON_VERSION",
          "ARG DOCKER_TAGS LAMBDA_APP_VERSION PYTHON_PIP_VERSION PYTHON_VERSION",
          "ARG DOCKER_IMAGE_NAME DOCKER_TAGS LAMBDA_APP_VERSION PYTHON_PIP_VERSION PYTHON_VERSION",
          "LABEL base.description=\"Lambda Runtime Interface Client for Python\"     vcs_url=\"https://github.intuit.com/dev-patterns/docker-oicp-debian-lambda-python.git\" \tdocker.label.com.intuit.debian11-lambda-python3.9_semantic_version=${LAMBDA_APP_VERSION} \tdocker.label.com.intuit.python_version=${PYTHON_VERSION} \tdocker.label.com.intuit.python_pip_version=${PYTHON_PIP_VERSION}",
          "ENV PATH /usr/local/bin:$PATH",
          "ENV LANG C.UTF-8",
          "USER root",
          "|5 DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/lambda/debian11-lambda-python:latest:1.0.2 DOCKER_TAGS=latest:1.0.2 LAMBDA_APP_VERSION=1.0.2 PYTHON_PIP_VERSION=22.0.4 PYTHON_VERSION=3.9.15 /bin/sh -c apt-get update && apt-get install -y --no-install-recommends \t\tbuild-essential \t\tzlib1g-dev \t\tlibncurses5-dev \t\tlibgdbm-dev \t\tlibnss3-dev \t\tlibssl-dev \t\tlibsqlite3-dev \t\tlibreadline-dev \t\tlibffi-dev \t\tcurl \t\tlibbz2-dev \t\twget \t\tg++ \t\tmake \t\tcmake \t\tunzip \t\tlibcurl4-openssl-dev \t&& rm -rf /var/lib/apt/lists/*",
          "ENV PYTHON_VERSION ${PYTHON_VERSION}",
          "|5 DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/lambda/debian11-lambda-python:latest:1.0.2 DOCKER_TAGS=latest:1.0.2 LAMBDA_APP_VERSION=1.0.2 PYTHON_PIP_VERSION=22.0.4 PYTHON_VERSION=3.9.15 /bin/sh -c wget -O Python-$PYTHON_VERSION.tgz \"https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tgz\" \t&& tar -xf Python-$PYTHON_VERSION.tgz \t&& cd Python-$PYTHON_VERSION \t&& ./configure --enable-optimizations \t&& make -j 2 \t&& make altinstall \t&& python3.9 --version \t&& rm /home/appuser/Python-${PYTHON_VERSION}/Lib/test/*.pem \t&& rm /home/appuser/Python-${PYTHON_VERSION}.tgz",
          "|5 DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/lambda/debian11-lambda-python:latest:1.0.2 DOCKER_TAGS=latest:1.0.2 LAMBDA_APP_VERSION=1.0.2 PYTHON_PIP_VERSION=22.0.4 PYTHON_VERSION=3.9.15 /bin/sh -c cd /usr/local/bin \t&& ln -s idle3.9 idle \t&& ln -s pydoc3.9 pydoc \t&& ln -s python3.9 python \t&& ln -s python3.9-config python-config",
          "ENV PYTHON_PIP_VERSION ${PYTHON_PIP_VERSION}",
          "ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/b60e2320d9e8d02348525bd74e871e466afdf77c/get-pip.py",
          "ENV PYTHON_GET_PIP_SHA256 c3b81e5d06371e135fb3156dc7d8fd6270735088428c4a9a5ec1f342e2024565",
          "|5 DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/lambda/debian11-lambda-python:latest:1.0.2 DOCKER_TAGS=latest:1.0.2 LAMBDA_APP_VERSION=1.0.2 PYTHON_PIP_VERSION=22.0.4 PYTHON_VERSION=3.9.15 /bin/sh -c set -ex; \t\twget -O get-pip.py \"$PYTHON_GET_PIP_URL\"; \techo \"$PYTHON_GET_PIP_SHA256 *get-pip.py\" | sha256sum --check --strict -; \t\tpython3.9 get-pip.py \t\t--disable-pip-version-check \t\t--no-cache-dir \t\t\"pip==$PYTHON_PIP_VERSION\" \t; \tpip --version; \t\tfind /usr/local -depth \t\t\\( \t\t\t\\( -type d -a \\( -name test -o -name tests -o -name idle_test \\) \\) \t\t\t-o \t\t\t\\( -type f -a \\( -name '*.pyc' -o -name '*.pyo' \\) \\) \t\t\\) -exec rm -rf '{}' +; \trm -f get-pip.py",
          "|5 DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/lambda/debian11-lambda-python:latest:1.0.2 DOCKER_TAGS=latest:1.0.2 LAMBDA_APP_VERSION=1.0.2 PYTHON_PIP_VERSION=22.0.4 PYTHON_VERSION=3.9.15 /bin/sh -c pip install awslambdaric",
          "ADD 335784840d2618b7178581135d97234f7db9c68e4a44059556c813da336e1a39 in /usr/bin/aws-lambda-rie",
          "COPY file:70e9f23c2bc010970874f7720b378aa1f606b18232f512568cfff0728a608210 in /",
          "|5 DOCKER_IMAGE_NAME=docker.intuit.com/oicp/standard/lambda/debian11-lambda-python:latest:1.0.2 DOCKER_TAGS=latest:1.0.2 LAMBDA_APP_VERSION=1.0.2 PYTHON_PIP_VERSION=22.0.4 PYTHON_VERSION=3.9.15 /bin/sh -c chmod 755 /usr/bin/aws-lambda-rie /entry.sh     && /home/appuser/post_harden.sh",
          "USER appuser",
          "ENTRYPOINT [ \"/entry.sh\" ]"
        ]
      }
    }
  }
]